### ISSUE TITLE
Running App.java as an application results in an error

### ISSUE THREAD

**Issue by viki85in** [josh28/kontext#1]
I have the latest code. Package runs correctly. But on running the App.java as an application, the following error gets thrown. 

It could be because I am not following the steps. Just wanted to clarify with you.
# Environment

cassandra version - 3.4
jdk 1.8.0_77
# Trace

17:09:54,340 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@33afa13b - Registering current configuration as safe fallback point
2016-04-07 17:09:54 [main] DEBUG o.k.c.r.PropertiesRepositoryImpl - Loading properties
2016-04-07 17:09:54 [main] DEBUG o.k.c.r.PropertiesRepositoryImpl - Loading properties complete
2016-04-07 17:09:54 [main] DEBUG o.k.c.r.PropertiesRepositoryImpl - Loading properties
2016-04-07 17:09:54 [main] DEBUG o.k.c.r.PropertiesRepositoryImpl - Loading properties complete
2016-04-07 17:09:54 [main] DEBUG o.k.c.r.PropertiesRepositoryImpl - Loading properties
2016-04-07 17:09:54 [main] DEBUG o.k.c.r.PropertiesRepositoryImpl - Loading properties complete
java.lang.Exception: couldn't create the storage folder: /data/crawl does it already exist ?
    at edu.uci.ics.crawler4j.crawler.CrawlController.<init>(CrawlController.java:98)
    at org.kontext.crawler.BasicController.start(BasicController.java:29)
    at org.kontext.runner.App.main(App.java:31)

**Comment by josh-petite** [comment]
Oh I'm sorry VIkram. I forgot to say that you need to create the folder /data/crawl locally (and maybe chmod 777 the crawl folder). This is bad but I didn't know how to make it use a relative path. I realize this will probably be a problem too if we jar this as it needs to write somewhere. How can we resolve this so the execution doesn't require outside paths?

**Comment by viki85in** [comment]
What about this - we can create a data.crawler path as a property - /tmp if it is just for temporary usage. May be even configure to use a different path if need be.

**Comment by josh-petite** [comment]
Perfect -- especially if that requires no additional work for the end user.

**Comment by viki85in** [comment]
Alright Cool. That ends that.
